name: Docker Hub to ECR

on:
  push:
    branches: [main]

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_IMAGE: lithu213/strapi-app
      ECR_IMAGE: 607700977843.dkr.ecr.us-east-2.amazonaws.com/strapi-ecr-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull image from Docker Hub
        run: docker pull $DOCKER_HUB_IMAGE:latest

      - name: Tag and push to ECR
        run: |
          docker tag $DOCKER_HUB_IMAGE:latest $ECR_IMAGE:latest
          docker push $ECR_IMAGE:latest
